### ISSUE TITLE
cli and api

### ISSUE THREAD

**Issue by Nllii** [akurgat/automating-technical-analysis#10]
Hello, are you open to turning this into a cli; 
then later on an Api;

if so, can you create 2 branches?

1. cli
2. docker

I don't want to touch the master branch.

**Comment by alexpvpmindustry** [comment]
you can fork the master and rename the branch to any name you want.

**Comment by Nllii** [comment]
![image](https://github.com/akurgat/automating-technical-analysis/assets/5082827/48ef3954-5104-45f7-9da3-9f09303d80a4)

**Comment by akurgat** [comment]
@Nllii 

No, I am not willing to make the changes to this repo at the moment. However, feel free to add any modifications you would like to the fork you have created.

**Comment by Nllii** [comment]
![image](https://github.com/akurgat/automating-technical-analysis/assets/5082827/649a7ecf-84ad-480a-8a0a-98dd97776e4b)

**Comment by Nllii** [comment]
![image](https://github.com/akurgat/automating-technical-analysis/assets/5082827/ea936e6c-27c7-4ebf-988f-fbf4b1d4bfdf)
