### ISSUE TITLE
[feature request] show results from backtesting

### ISSUE THREAD

**Issue by alexpvpmindustry** [akurgat/automating-technical-analysis#11]
is it possible to show the results from backtesting along side with the percentage chance of being correct?
i feel that this is an important way to show the accuracy of the predictions.

the backtest could be done on 95% of the historical data within the time frame selected.

**Comment by akurgat** [comment]
I have included the requesed feature.  Any further details are in the description of commit 35b16cb.

**Comment by alexpvpmindustry** [comment]
backtesting is not the same as prediction price.
backtesting is testing the trained transformer on historical data to determine the profit it made using the algorithm.
the percentage accuracy is not good enough because for example, you can be right 95% of the time, winning $1 total, but the last 5% you can lose $100.

**Comment by alexpvpmindustry** [comment]
maybe i rephrase my question.
for example, if you start with $100 at the beginning of the year and follow the buy and sell signals, how much will you profit(or lose) 3 months later (in march)?

**Comment by akurgat** [comment]
Your proposal sounds more plausible in conjunction with a specified trading strategy on trading a specified asset class. 

That goes far and beyond the motivation and desired purpose for this project. Its structure and approach is a lot more general than what you are suggesting.

However, its backend structure can be used as a framework to build on trading strategies that can deliver your stated result. Though that’s a whole other project on its own, requiring a lot of trading expertise and I am not intending to further this project in that direction.
